# 추가 퀴즈

- 1) 1~15 구성된 넘파이 배열을 3행 5열로 구성하고 1,3,5 열만 출력하여라 
- 2) 1~15 구성된 넘파이 배열을 3행 5열로 구성하고 1행1열, 1행4열, 3행1열, 3행 4열만 출력하여라 
- 3) 1~15 구성된 넘파이 배열을 3행 5열로 구성하고 홀수번째 행만 출력하여라

In [2]:
import numpy as np
from sympy import Symbol, solve, Derivative, diff

In [3]:
arr1 = np.arange(1,16).reshape(3,5)
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [4]:
# 1)
arr1[::,::2]

array([[ 1,  3,  5],
       [ 6,  8, 10],
       [11, 13, 15]])

In [5]:
# 2)
arr1[:3:2,:4:3]

array([[ 1,  4],
       [11, 14]])

In [6]:
# 3)
arr1[::2,::]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [8]:
arr1[0,0], arr1[0,3], arr1[2,0], arr1[2,3]

(1, 4, 11, 14)