# 퀴즈 

- 1. data.csv 파일에서 1행과 학생컬럼을 제외한 숫자 데이타만 넘파이 배열로 생성하여라. 
- 2. 1의 넘파이 배열에서 수학 점수와 과학 점수의 평균과 편차를 구하여라. 
- 3. 1의 넘파이 배열에서 1반(class가 1)의 국어, 영어, 수학, 과학 데이타만 추출하여 별도의 넘파이 배열로 생성하여라
- 4. 3의 결과로 생성된 배열에서 각 과목의 평균을 구하여라

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statistics as st

In [2]:
ls data 

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 3089-74F2

 c:\class\data 디렉터리

2021-11-17  오후 03:04    <DIR>          .
2021-11-17  오후 03:04    <DIR>          ..
2021-11-17  오후 02:31               263 data.csv
               1개 파일                 263 바이트
               2개 디렉터리  432,648,728,576 바이트 남음


In [3]:
student1 = np.loadtxt('data/data.csv', delimiter=',', dtype=str)
student1

array([['class', 'name', 'kor', 'eng', 'mat', 'bio'],
       ['1', 'adam', '67', '87', '90', '98'],
       ['1', 'andrew', '45', '45', '56', '98'],
       ['1', 'ben', '95', '59', '96', '88'],
       ['1', 'clark', '65', '94', '89', '98'],
       ['1', 'dan', '45', '65', '78', '98'],
       ['1', 'noel', '78', '76', '98', '89'],
       ['2', 'paul', '87', '67', '65', '56'],
       ['2', 'walter', '89', '98', '78', '78'],
       ['2', 'oscar', '100', '78', '56', '65'],
       ['2', 'martin', '99', '89', '87', '87'],
       ['2', 'hugh', '98', '45', '56', '54'],
       ['2', 'henry', '65', '89', '87', '78']], dtype='<U6')

In [4]:
# 1)
student2 = np.loadtxt('data/data.csv', 
                      delimiter=',', 
                      dtype=int,
                      skiprows=1, 
                      usecols=[0, 2, 3, 4, 5])
student2

array([[  1,  67,  87,  90,  98],
       [  1,  45,  45,  56,  98],
       [  1,  95,  59,  96,  88],
       [  1,  65,  94,  89,  98],
       [  1,  45,  65,  78,  98],
       [  1,  78,  76,  98,  89],
       [  2,  87,  67,  65,  56],
       [  2,  89,  98,  78,  78],
       [  2, 100,  78,  56,  65],
       [  2,  99,  89,  87,  87],
       [  2,  98,  45,  56,  54],
       [  2,  65,  89,  87,  78]])

In [5]:
# 2)
np.mean(student2[:, 3]), np.mean(student2[:,4])

(78.0, 82.25)

In [6]:
np.std(student2[:, 3]), np.std(student2[:,4])

(15.198684153570664, 15.583778959760263)

In [51]:
# 3)
student3 = student2[:6:,1:]
student3

array([[67, 87, 90, 98],
       [45, 45, 56, 98],
       [95, 59, 96, 88],
       [65, 94, 89, 98],
       [45, 65, 78, 98],
       [78, 76, 98, 89]])

In [46]:
student4 = student2[student2[:,0] == 1]
student4 = student4[:,1:]
student4

array([[67, 87, 90, 98],
       [45, 45, 56, 98],
       [95, 59, 96, 88],
       [65, 94, 89, 98],
       [45, 65, 78, 98],
       [78, 76, 98, 89]])

In [53]:
# 4)
np.mean(student3, axis=0)

array([65.83333333, 71.        , 84.5       , 94.83333333])